/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'majie' at '16-11-11 下午5:49' with Gradle 3.1
 *
 * @author majie, @date 16-11-11 下午5:49
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
